apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: registry.kkserver.net/pocket-tarot-server
    newName: registry.kkserver.net/pocket-tarot-server
    newTag: dev-placeholder
